version: '0.1'

services:
  drone-server:
    image: drone/drone:1
    restart: always
    environment:
      - DRONE_GITHUB_CLIENT_ID
      - DRONE_GITHUB_CLIENT_SECRET
      - DRONE_RPC_SECRET
      - DRONE_SERVER_HOST
      - DRONE_SERVER_PROTO
      - DRONE_TLS_AUTOCERT
    ports:
      - "80:80"
      - "443:443"
  drone-runner:
    image: drone/drone-runner-docker:1
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_RPC_PROTO
      - DRONE_RPC_HOST
      - DRONE_RPC_SECRET
      - DRONE_RUNNER_CAPACITY
      - DRONE_RUNNER_NAME
    ports:
      - "3000:3000"